### ISSUE TITLE
Web not accessible after installation

### ISSUE THREAD

**Issue by dj-wasabi** [thomas-maurice/ansible-role-gitea#111]
Hi,

Just deployed this Gitea role, with the following variables set in group_vars:
```yml
gitea_version: "1.16.7"
gitea_home: /opt/data/gitea
gitea_http_domain: gitea.mydomain.com
gitea_ssh_domain: gitea.mydomain.com
# gitea_http_listen: 10.10.1.10
gitea_http_listen: 0.0.0.0
gitea_ssh_port: 2223
# gitea_root_url: https://gitea.mydomain.com:3000
gitea_root_url: https://gitea.mydomain.com
gitea_protocol: https
```

But after execution, I am only able to access port 2223 (telnet), but not port 3000. No firewall loaded/running.
```sh
root@control:~# netstat -tlpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 10.10.1.10:53           0.0.0.0:*               LISTEN      14010/named
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      618/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1339/sshd: /usr/sbi
tcp        0      0 127.0.0.1:953           0.0.0.0:*               LISTEN      14010/named
tcp6       0      0 :::2223                 :::*                    LISTEN      25255/gitea
tcp6       0      0 ::1:53                  :::*                    LISTEN      14010/named
tcp6       0      0 :::22                   :::*                    LISTEN      1339/sshd: /usr/sbi
tcp6       0      0 ::1:953                 :::*                    LISTEN      14010/named
root@control:~# curl https://gitea.mydomain.com:3000
curl: (7) Failed to connect to gitea.mydomain.com port 3000: Connection refused
root@control:~# curl https://localhost:3000
curl: (7) Failed to connect to localhost port 3000: Connection refused
root@control:~# ping gitea.mydomain.com
PING control01.mydomain.com (10.10.1.10) 56(84) bytes of data.
64 bytes from control (10.10.1.10): icmp_seq=1 ttl=64 time=0.075 ms
^C
--- control01.mydomain.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.075/0.075/0.075/0.000 ms
root@control:~#
```

Running Ubuntu 20.04. What am I doing wrong? (I am not using a Web proxy)
