### ISSUE TITLE
Version check fails silently due -o pipefail

### ISSUE THREAD

**Issue by msgpeek** [thomas-maurice/ansible-role-gitea#48]
The version check command with set -eo pipefail fails silently. 

Relevant output of ansible -vvv on Debian Buster:

```yaml
"msg": "non-zero return code",
"rc": 2,
"start": "2020-06-15 02:59:18.807048",
"stderr": "/bin/sh: 1: set: Illegal option -o pipefail",
"stderr_lines": [  
"/bin/sh: 1: set: Illegal option -o pipefail" 
],
```
The problem was already discussed in https://github.com/ansible/ansible-lint/issues/497.

Short: there is no guarantee which shell Ansible uses on which distro and -o pipefail is not likely to be supported.
The solution could be leaving it out or using suggestion from https://github.com/ansible/ansible-lint/issues/497#issuecomment-477141267. 

Despite pipefail being best practice, I tend to support the former. Having checks for bash, although likely to be present, require bash to be installed.
